[theme]
primaryColor = "#2e7d32"  # Zelena barva za vrtnarjenje
backgroundColor = "#f8fff8"
secondaryBackgroundColor = "#e8f5e9"
textColor = "#1b5e20"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
